name: CI

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.4.0"

      - name: 📦 Instalar dependências
        run: npm install

      - name: 🧬 Run Prisma Generate
        run: npx prisma generate

      - name: 🛠️ Build do projeto
        run: npm run build
